import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'khouloudmk96@gmail.com',
      password: bcrypt.hashSync('admin123'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'mamloukkhouloud07@example.com',
      password: bcrypt.hashSync('user123'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Ampoule Serum',
      slug: 'Ampoule-Serum',
      category: 'Korean products',
      query: 'serum',
      image: 'https://i.imgur.com/spECf78.jpg', // img dimension 540 x 720 px
      price: 132,
      stock: 10,
      brand: 'CQMONG',
      rating: 4.5,
      numReviews: 0,
      description:
        'High Quality Serum made of 78 effective ingredients for intensive Moisture & Brilliance ',
    },

    {
      name: 'Intensive Eye Cream',
      slug: 'Eye-Cream',
      category: 'Korean products',
      query: 'cream',
      image: 'https://i.imgur.com/FYVWwzX.jpg',
      price: 131,
      stock: 30,
      brand: 'CQMONG',
      rating: 5.0,
      numReviews: 0,
      description:
        'Intensive Eye Cream that contains a total of 83 Highly Concentrated ingredients for a clear and vital effect.',
    },

    {
      name: 'Diamond Ampoule Sheet Mask',
      slug: 'Sheet-Mask',
      category: 'Korean products',
      query: 'mask',
      image: 'https://i.imgur.com/Fi9pRVi.jpg',
      price: 15,
      stock: 40,
      brand: 'CQMONG',
      rating: 4.0,
      numReviews: 0,
      description:
        'Diamond Ampoule Sheet Mask contains a total of 65 ingredients which makes your Skin vital, moistured and soothed.',
    },

    {
      name: 'Hyaluronic Acid Secret Gel Cleanser',
      slug: 'Gel-Cleanser',
      category: 'Korean products',
      query: 'cleanser',
      image: 'https://i.imgur.com/csw9Vfj.jpg',
      price: 107,
      stock: 10,
      brand: 'K-SECRET',
      rating: 5.0,
      numReviews: 0,
      description:
        'Hyaluronic Acid Secret Gel Cleanser is a gentle Water based face cleanser contains 6 types of hyaluronic acids for effective daily face cleansing.',
    },

    {
      name: 'Hyaluronic Acid Secret Toner',
      slug: 'Secret-Toner',
      category: 'Korean products',
      query: 'toner',
      image: 'https://i.imgur.com/A1tA9lg.jpg',
      price: 107,
      stock: 20,
      brand: 'K-SECRET',
      rating: 4.5,
      numReviews: 0,
      description:
        'Hyaluronic Acid Secret Toner is an instant Skin Soothing with Water Balance Restore toner that contains 6 types of hyaluronic acids for effective hydration.',
    },

    {
      name: 'Hyaluronic Acid Secret Sun Cushion',
      slug: 'Sun-Cushion',
      category: 'Korean products',
      query: 'sunscreen',
      image: 'https://i.imgur.com/mrpg5Rn.jpg',
      price: 169,
      stock: 10,
      brand: 'K-SECRET',
      rating: 5.0,
      numReviews: 0,
      description:
        'Hyaluronic Sun Cushion SPF 50+ contains 8 types of Hyaluronic Acids for powerful soothing effect for sun-irritated skin.',
    },

    {
      name: 'Ultra-Light Invisible Sunscreen',
      slug: 'Invisible-Sunscreen',
      category: 'Korean products',
      query: 'sunscreen',
      image: 'https://i.imgur.com/H8lTfcJ.jpg',
      price: 105,
      stock: 30,
      brand: 'COSRX',
      rating: 4.0,
      numReviews: 0,
      description:
        'A Moisturising Sunscreen with SPF50+ with an ultra-thin consistency and a transparent formula that is absorbed quickly without leaving white spots.',
    },

    {
      name: 'Ultimate Nourishing Rice Spa Overnight Mask',
      slug: 'Overnight-Mask',
      category: 'Korean products',
      query: 'mask',
      image: 'https://i.imgur.com/wowvKy7.jpg',
      price: 125,
      stock: 20,
      brand: 'COSRX',
      rating: 5.0,
      numReviews: 0,
      description:
        'Ultimate Nourishing Rice Spa Overnight Mask is enriched with more than 65% of rice extract, which contains a variety of vitamins and minerals for intensive nourishment and deep moisture',
    },

    {
      name: 'Oil-Free Ultra-Moisturizing Lotion with Birch Sap',
      slug: 'Moisturizing-Lotion',
      category: 'Korean products',
      query: 'lotion',
      image: 'https://i.imgur.com/P5Y5QLt.jpg',
      price: 130,
      stock: 40,
      brand: 'COSRX',
      rating: 4.5,
      numReviews: 0,
      description:
        'Oil Free Ultra Moisturizing Lotion is a lightweight lotion formulated with 70.8% birch sap to hydrate and calm skin effectively.',
    },

    {
      name: 'Lacto Soy Sebum and Blackhead Cleansing Oil',
      slug: 'Cleansing-Oil',
      category: 'Korean products',
      query: 'cleansing oil',
      image: 'https://i.imgur.com/mKPI1EZ.jpg',
      price: 125,
      stock: 10,
      brand: 'innisfree',
      rating: 5.0,
      numReviews: 0,
      description:
        'Lacto Soy Sebum Blackhead Cleansing Oil is a gentle yet effective cleansing oil that helps remove blackheads and excess sebum.',
    },

    {
      name: 'Lacto Soy Mild Peeling Bubble Cleanser',
      slug: 'Bubble-Cleanser',
      category: 'Korean products',
      query: 'cleanser',
      image: 'https://i.imgur.com/GK4zGak.jpg',
      price: 120,
      stock: 20,
      brand: 'innisfree',
      rating: 4.5,
      numReviews: 0,
      description:
        'The Lacto Soy Mild Peeling Bubble Cleanser by Some By Mi is a gentle and nourishing cleanser that helps to purify the skin and remove impurities.',
    },

    {
      name: 'Lacto Soy Low pH Morning Cleansing Bar',
      slug: 'Cleansing-Bar',
      category: 'Korean products',
      query: 'cleansing bar',
      image: 'https://i.imgur.com/YDk6LLE.jpg',
      price: 65,
      stock: 15,
      brand: 'innisfree',
      rating: 0,
      numReviews: 0,
      description:
        'Lacto Soy Low pH Morning Cleansing Bar is a gentle, fragrance-free, non-comedogenic and moisturizing Korean low pH bar soap cleanser for all skin types.',
    },
    {
      name: 'Green Plum Refreshing Cleanser',
      slug: 'Green-Cleanser',
      category: 'Korean products',
      query: 'cleanser',
      image: 'https://i.imgur.com/SZl6zCr.jpg',
      price: 96,
      stock: 10,
      brand: 'Beauty of Joseon',
      rating: 4.5,
      numReviews: 0,
      description:
        'Green Plum Refreshing Cleanser is a low-pH gel-type cleanser containing oriental herbal ingredients to protect your skin natural skin barrier while cleansing.',
    },
    {
      name: 'Calming Serum : Green tea + Panthenol',
      slug: 'Green-Serum',
      category: 'Korean products',
      query: 'Serum',
      image: 'https://i.imgur.com/fXnYe7d.jpg',
      price: 113,
      stock: 5,
      brand: 'Beauty of Joseon',
      rating: 4.0,
      numReviews: 0,
      description:
        'This serum is formulated to alleviate skin discomfort caused by UV exposure and other external stressors. It contains 79% green tea extract and 2% panthenol to soothe and hydrate the skin.',
    },
    {
      name: 'Radiance Cleansing Balm',
      slug: 'Cleansing-Balm',
      category: 'Korean products',
      query: 'cleansing balm',
      image: 'https://i.imgur.com/RPzphFW.jpg',
      price: 117,
      stock: 15,
      brand: 'Beauty of Joseon',
      rating: 3.5,
      numReviews: 0,
      description:
        'It is a balm-type cleansing oil that gently melts eye, lip, base makeup and sebum. It contains rice bran and various grain extracts, so the skin does not get dry and remains moist.',
    },
    {
      name: 'Madagascar Centella Ampoule Foam Cleanser',
      slug: 'Centella-Cleanser',
      category: 'Korean products',
      query: 'cleanser',
      image: 'https://i.imgur.com/acpWdFo.jpg',
      price: 110,
      stock: 12,
      brand: 'SKIN 1004',
      rating: 4.5,
      numReviews: 0,
      description:
        'Madagascar Centella Ampoule Foam is a rich, foaming cleanser with the ideal pH level of 5 effectively remove makeup and impurities without stripping the skin.',
    },
    {
      name: 'Madagascar Centella Toning Toner',
      slug: 'Centella-Toner',
      category: 'Korean products',
      query: 'toner',
      image: 'https://i.imgur.com/1iCaCWe.jpg',
      price: 135,
      stock: 20,
      brand: 'SKIN 1004',
      rating: 5.0,
      numReviews: 0,
      description:
        'The SKIN1004 Madagascar Centella Toning Toner is a gentle exfoliating toner that can be used daily to help exfoliate dead skin cells and is suitable for sensitive skin. ',
    },
    {
      name: 'Madagascar Centella Ampoule 100 ml',
      slug: 'Centella-Ampoule',
      category: 'Korean products',
      query: 'ampoule ',
      image: 'https://i.imgur.com/cjQT6bC.jpg',
      price: 160,
      stock: 10,
      brand: 'SKIN 1004',
      rating: 4.5,
      numReviews: 0,
      description:
        'The SKIN1004 Madagascar Centella Ampoule helps to rejuvenate skin thanks to its soothing and softening properties. It is formulated with 100% Centella Asiatica extract from Madagascar, which is known for its healing properties.',
    },
    {
      name: 'Heartleaf Silky Moisture Sun Cream',
      slug: 'Sun-Cream',
      category: 'Korean products',
      query: 'sunscreen',
      image: 'https://i.imgur.com/NvjDSna.jpg',
      price: 110,
      stock: 10,
      brand: 'ANUA',
      rating: 4.5,
      numReviews: 0,
      description:
        'Heartleaf Silky Moisture Sun Cream is a lightweight organic sunscreen that provides soothing and hydrating benefits. It contains 70% Heartleaf extract, which is known for its anti-inflammatory properties.',
    },
    {
      name: 'Anua Rice 7 Ceramide Hydrating Barrier Serum',
      slug: 'Rice-Serum',
      category: 'Korean products',
      query: 'serum',
      image: 'https://i.imgur.com/MnlYxrm.jpg',
      price: 140,
      stock: 8,
      brand: 'ANUA',
      rating: 5.0,
      numReviews: 0,
      description:
        "Discover the secret to a luminous, hydrated complexion. Anua's Rice and Ceramide Serum is a transformative elixir that replenishes your skin's natural moisture barrier while illuminating your complexion. ",
    },
    {
      name: 'Heartleaf Pore Clay Pack',
      slug: 'Clay-Mask',
      category: 'Korean products',
      query: 'mask',
      image: 'https://i.imgur.com/zZENJsQ.jpg',
      price: 90,
      stock: 15,
      brand: 'ANUA',
      rating: 3.5,
      numReviews: 0,
      description:
        'Anua Heartleaf Pore Clay Pack is a gentle pore-care clay mask formulated with Bentonite and Kaolin to unclog pores and exfoliate skin for a smooth finish. It contains 70% Heartleaf extract to soothe and calm the skin, making it suitable for all skin types, including sensitive skin.',
    },
    {
      name: 'Yuja Niacin Brightening Moisture Gel Cream',
      slug: 'Yuja-Cream',
      category: 'Korean products',
      query: 'Cream',
      image: 'https://i.imgur.com/b8e3wYs.jpg',
      price: 117,
      stock: 5,
      brand: 'SOME BY MI',
      rating: 5.0,
      numReviews: 0,
      description:
        'The Some By Mi Yuja Niacin Brightening Moisture Gel Cream, contains 90% of Yuja Extract to nourish and moisturize the skin. Yuja is a type of citrus that is rich in vitamins and effective for brightening. It also contains Niacinamide, which is known for its brightening and anti-aging properties.',
    },
    {
      name: 'Charcoal BHA Pore Clay Bubble Mask',
      slug: 'Charcoal-Mask',
      category: 'Korean products',
      query: 'mask',
      image: 'https://i.imgur.com/mEhWLcN.jpg',
      price: 95,
      stock: 20,
      brand: 'SOME BY MI',
      rating: 3.5,
      numReviews: 0,
      description:
        'The Some By Mi Charcoal BHA Pore Clay Bubble Mask is a skin-purifying wash off mask that improves skin texture and tone. Formulated with Charcoal Extract and Kaolin, it effectively removes any dead skin cells, sebum and oil in your pores while refining enlarged pores. ',
    },
    {
      name: 'Yuja Niacin 30 Days Blemish Care Serum',
      slug: 'Yuja-Serum',
      category: 'Korean products',
      query: 'serum',
      image: 'https://i.imgur.com/yBx7y8T.jpg',
      price: 130,
      stock: 10,
      brand: 'SOME BY MI',
      rating: 4.5,
      numReviews: 0,
      description:
        'This serum brightens dull and uneven skin tone by targeting blemishes, freckles and pigmentation to create a fresh and dewy complexion. Formulated with yuja extract and niacinamide for brightening and moisturizing effects, glutathione and arbutin to lighten dark spots and prevent melanin pigment production, as well as 12 types of vitamins to revitalize and relieve dull and stressed skin. ',
    },
  ],
};

export default data;
